### ISSUE TITLE
Home Locks Up When Changing Various Phone Options

### ISSUE THREAD

**Issue by 0pLuS0** [amirzaidi/Launcher3#522] opened 2018-07-14 01:37 UTC
Hi,

I'm using a ```Xiaomi Mi A1``` with the ```AospExtended ROM version 5.7``` that uses your Pixel Launcher. 

https://downloads.aospextended.com/tissot/

I don't know what version of the Launcher the AEX ROM uses, but in both AEX ROMs, 5.6 & 5.7 I have been having this problem. It seems to be a launcher issue, because if I change launchers the problem doesn't appear.

If I change a wallpaper, or UI style, then pressing the Home screen to bring up the options; Wallpapers - Widgets - Settings, does not work, the Home screen I would say, because it's not working is now frozen.

I can reproduce this problem 100% every time, it always happens.

1. Settings > Display > Advanced > System Theme > UI style - change a theme, now Home not working.

2. Press Home and wait for options to appear, press wallpaper and set a wallpaper, now Home not working

The only way I get the Home press to work again, I need to restart the phone.

I submitted logcats to the developer of AEX, and I was told he could not find any issues in the logs.

I'm attaching logcats I submitted to the developer...

[logcat_1.txt](https://github.com/amirzaidi/Launcher3/files/2194556/logcat_1.txt)

[logcat_2.txt](https://github.com/amirzaidi/Launcher3/files/2194557/logcat_2.txt)

[logcat_3.txt](https://github.com/amirzaidi/Launcher3/files/2194558/logcat_3.txt)

[logcat_4.txt](https://github.com/amirzaidi/Launcher3/files/2194559/logcat_4.txt)

Thank you

**Comment by amirzaidi** [comment] 2018-07-14 12:17
I've seen this issue before, what happens if you force close the launcher?

**Comment by 0pLuS0** [comment] 2018-07-14 13:24
@amirzaidi force close it, in what manner, please explain the steps?

All I know is to go to Apps and Disable...

Thanks

**Comment by amirzaidi** [comment] 2018-07-14 14:32
Go to Apps -> Pixel Launcher then click Force Stop

---

The developer is right btw, those logcats are not useful, but an issue like this doesn't show up in logcats anyways. I know it has to do with the setWorkspaceLoading call in onCreate that blocks input until the launcher has loaded, but that should not bug out under normal circumstances.

**Comment by 0pLuS0** [comment] 2018-07-14 22:16
@amirzaidi, sorry about the Force Stop, LOL, it was late when I asking, must of been in a brain haze...

Ok I did the Force Stop and it's working again, so does that help you understand why it might be locking up in the first place?

Or why would it lock up setting wallpaper, or changing UI, any ideas?

I really hope you can resolve this, really bothersome to have to force stop, or restart to get it working again...

Thanks

**Comment by 0pLuS0** [comment] 2018-07-15 00:59
@amirzaidi, sorry about the Force Stop, LOL, it was late when I asking, must of been in a brain haze...

I really hope you can resolve this, really bothersome to have to force stop, or restart to get it working again...

Thanks

```P.S. Something else just happened, the App Drawer become translucent, and it's always been white... hmm```

**Comment by 0pLuS0** [comment] 2018-07-15 01:00
@amirzaidi, sorry about the Force Stop, LOL, it was late when I asking, must of been in a brain haze...

```Force Stop worked...```

I really hope you can resolve this, really bothersome to have to force stop, or restart to get it working again...

Thanks

```P.S. Something else just happened, the App Drawer become translucent, and it's always been white... hmm```

**Comment by 0pLuS0** [comment] 2018-07-15 01:00
@amirzaidi, sorry about the Force Stop, LOL, it was late when I asking, must of been in a brain haze...

```Force Stop worked...```

I really hope you can resolve this, really bothersome to have to force stop, or restart to get it working again...

Thanks

```P.S. Something else just happened, the App Drawer became translucent, and it's always been white... hmm```

**Comment by 0pLuS0** [comment] 2018-07-15 01:03
@amirzaidi, sorry about the Force Stop, LOL, it was late when I asked, guess I was sleepy and not thinking.

```Force Stop worked...```

I really hope you can resolve this, really bothersome to have to force stop, or restart to get it working again...

Thanks

```P.S. Something else just happened, the App Drawer became translucent, and it's always been white... hmm```

**Comment by amirzaidi** [comment] 2018-07-15 13:26
Can you try my latest alpha build from Telegram? I don't know if the AEX developer changed the internal code so I'll need to make sure this is reproducible my builds

**Comment by 0pLuS0** [comment] 2018-07-15 23:11
@amirzaidi if you're talking about the app Telegram I don't use it, so where can I get this?

**Comment by 0pLuS0** [comment] 2018-07-15 23:38
@amirzaidi Telegram, as in telegram.org? I thought that is just a messenger app? Hmm

Anyhow if you are talking about that Telegram I don't use it, so where else can I get this?

**Comment by 0pLuS0** [comment] 2018-07-15 23:39
@amirzaidi Telegram, as in telegram.org? I thought that is just a messenger app? Hmm

Anyhow if you are talking about that Telegram I don't use it, so where else can I get this?

If you have another Developer Branch, why isn't it on GitHub?

**Comment by 0pLuS0** [comment] 2018-07-15 23:46
@amirzaidi Telegram, as in telegram.org? I thought that is just a messenger app? Hmm

Anyhow if you are talking about that Telegram I don't use it, so where else can I get this?

If you have another Developer Branch, why isn't it on GitHub?

Is this what you meant? https://t.me/appforks

But like I said, I don't use Telegram.

**Comment by 0pLuS0** [comment] 2018-07-18 00:59
@amirzaidi I don't use Telegram, can you please put this alpha build up on GitHub?

Thanks

**Comment by amirzaidi** [comment] 2018-07-18 23:00
It's released as 3.6 now.

**Comment by 0pLuS0** [comment] 2018-07-19 02:11
@amirzaidi it won't install... :(

The version in this rom says 8.1.0

Here are some screen shots attached...

![l_1](https://user-images.githubusercontent.com/36190223/42917434-069dacf0-8af9-11e8-89f0-85b08bc86812.jpg)


![l_2](https://user-images.githubusercontent.com/36190223/42917436-0a916248-8af9-11e8-8f2a-7401c07c3413.jpg)


![l_3](https://user-images.githubusercontent.com/36190223/42917439-0d78f304-8af9-11e8-8fbb-5d9581b9058d.jpg)

**Comment by 0pLuS0** [comment] 2018-07-19 02:42
By the way 3.6 comes up infected on some scanners;

PUP.HighConfidence

**Comment by 0pLuS0** [comment] 2018-07-19 02:54
@amirzaidi I installed 3.6, didn't realize needed to uninstall the older version first.

But what happened to all the Settings/Options?

Now I only have a ```Home settings``` and this is all the options;

Notification dots
At A Glance
Add icon to Home screen
Display App Suggestions
Allow Home screen rotation
Theme
Change icon shape
Icon pack 
About

There is no longer an option to remove the Swipe Up Arrow, or the Search at the bottom of the screen.... :face_with_head_bandage: 

By the way 3.6 comes up infected on some scanners;

PUP.HighConfidence

**Comment by 0pLuS0** [comment] 2018-07-19 03:04
@amirzaidi I installed 3.6, didn't realize needed to uninstall the older version first.

But what happened to all the Settings/Options?

Now I only have a ```Home settings``` and this is all the options;

Notification dots
At A Glance
Add icon to Home screen
Display App Suggestions
Allow Home screen rotation
Theme
Change icon shape
Icon pack 
About

By the way ```At A Glance``` seems to be a odd name to use for the Date? Hmm

There is no longer an option to remove the Swipe Up Arrow, or the Search at the bottom of the screen.... 

Ahh where did all these options go? :face_with_head_bandage: 

I installed ```Launcher3-aosp-optimized.apk```

The App Drawer is also completely translucent, there really needs to be an option to adjust this. 

By the way 3.6 comes up infected on some scanners;

PUP.HighConfidence

```P.S. Almost forgot, on a good report, it is no longer locking up``` :+1:

**Comment by amirzaidi** [comment] 2018-07-19 14:28
All the other customization has been added by AEX, I've never been heavy on customization. If my version does not lock up then this is a bug introduced by AEX and I cannot fix it.

**Closed as completed by amirzaidi** 2018-07-19 14:28 UTC

**Comment by amirzaidi** [comment] 2018-07-19 14:29
As for the reason behind the PUP detection, it might be because of the heavy proguard optimization. A clean build from GitHub sources still gets detected so 🤷

**Comment by 0pLuS0** [comment] 2018-07-20 01:20
@amirzaidi, ok on the lockup, but it sure would be appreciated if you can just add in only a few  options, and the Date should truly be added in, no one should be stuck having a Date on the Home if they don't want it.

Also please consider to remove the ```Up Swipe Arrow``` and removing the ```Search Bar``` at the bottom. I forgot also if the dock is transparent or not, but having the ability to change opacity in a dock is pretty common.

I hope you don't consider these changes, as you mentioned ```heavy on customization```, I certainly don't, because, they are certainly not worthless bloated options.

Don't take me the wrong way, I'm just here to share and help, and I've been around Android since it started, way before Google stepped on the scene, and the launcher as it stands right now, almost comes across like it's still in development missing features. It doesn't even seem completed, with these options I mentioned, needing added in.

Ok on the PUP too...

Thanks
