### ISSUE TITLE
Icons disappearing until force restart of launcher

### ISSUE THREAD

**Issue by tysonseable** [amirzaidi/Launcher3#440] opened 2018-03-29 05:37 UTC
On my unlocked Moto G4 Play, some of my installed apps disappear from the launcher causing me to force restart the app to bring them back. I am using an icon pack, and I have a few hidden apps. Not sure if this contributes to the issue or not.

**Comment by amirzaidi** [comment] 2018-03-29 09:27
Duplicate of https://github.com/amirzaidi/Launcher3/issues/388

**Closed as completed by amirzaidi** 2018-03-29 09:27 UTC
