### ISSUE TITLE
Can not swipe card away any longer

### ISSUE THREAD

**Issue by JostCrow** [amirzaidi/Launcher3#467] opened 2018-04-17 12:06 UTC
Since version 3 I can no longer swipe the cards away any more. Should this still be possible or is it removed?

Android: 8.0.0
Launcher3: 3.4

**Comment by mincaeuro** [comment] 2018-04-18 08:55
got the same problem
Android: 6.0.1
Launcher3: 3.4

**Comment by dbesoli** [comment] 2018-04-18 09:22
this is duplicate of this https://github.com/amirzaidi/Launcher3/issues/371
and it's the normal behaviour for Google app

**Closed as completed** 2018-04-18 17:07 UTC
