### ISSUE TITLE
App drawer blue bakground

### ISSUE THREAD

**Issue by eturk1** [amirzaidi/Launcher3#245] opened 2017-09-21 05:54 UTC
App drawer has blue background, not light grey, can't read text.

![screenshot_20170920-223701](https://user-images.githubusercontent.com/525280/30680771-5c767c96-9e56-11e7-85c7-fbd610cdac98.png)

## Environment
* Device: Samsung Galaxy S2 tablet 2016
* Android version: 7.0.0
* Launcher version: 2.1
* Rom: stock

**Comment by abdullahibneat** [comment] 2017-09-21 06:25
Try clearing cache and rebooting your device.

**Comment by RikKoedoot** [comment] 2017-09-21 19:07
this is a known issue, read #112

**Comment by abdullahibneat** [comment] 2017-09-21 19:18
@rickkode I think you linked the wrong issue

**Comment by eturk1** [comment] 2017-09-21 19:19
#112 is about "suggestions" in app drawer

**Comment by Rishoj** [comment] 2017-09-30 13:01
This is a duplicate of #122, not #112.

**Closed as completed** 2018-01-27 14:02 UTC
Labels: bug
