### ISSUE TITLE
Notification dots bug

### ISSUE THREAD

**Issue by floppyD** [amirzaidi/Launcher3#346] opened 2018-02-07 23:51 UTC
It happens randomly. I uploaded a video that describes the issue pretty well.
https://youtu.be/kifFwQL7mgw

**Comment by stek-kravari** [comment] 2018-02-08 18:41
I have the same problem. Please fix

**Comment by amirzaidi** [comment] 2018-03-24 00:24
Duplicate of https://github.com/amirzaidi/Launcher3/issues/202

**Closed as completed by amirzaidi** 2018-03-24 00:24 UTC
