### ISSUE TITLE
Clear Icon Background

### ISSUE THREAD

**Issue by keetrock46270** [amirzaidi/Launcher3#65] opened 2017-06-17 21:14 UTC
Is it possible to have the background for the icons like Google Play, Gmail and YouTube clear?

**Comment by zeevox** [comment] 2017-06-18 15:11
Basically, you don't want Pixel round icons. 

Duplicate of #68 / please merge

**Comment by RikKoedoot** [comment] 2017-06-18 15:18
He doesn't want dinner plates

**Comment by keetrock46270** [comment] 2017-06-18 16:11
The round icons are fine...I know on the pixel launcher, the backgrounds are clear or semi clear on the icons like YouTube, Gmail, Play Store.

**Comment by zeevox** [comment] 2017-06-18 16:12
@keetrock46270 I don't understand what you mean. On the Google Pixel, Pixel Launcher shows round icons which have backgrounds as per the decision of the application developer.

**Comment by keetrock46270** [comment] 2017-06-18 16:20
Here is a screenshot of my old pixel launcher. Notice the icons for Play,
YouTube and Gmail do not have a white background...maybe that's the dinner
plate the other was talking about.

**Comment by zeevox** [comment] 2017-06-18 16:24
@keetrock46270 Can't see any screenshot... Do you mean that you want the YouTube icon like this: [v1] <br>
![youtube-default](http://www.apkmirror.com/wp-content/themes/APKMirror/ap_resize/ap_resize.php?src=http%3A%2F%2Fwww.apkmirror.com%2Fwp-content%2Fuploads%2F2017%2F06%2F5943da67e8f5e.png&w=128&h=128&q=100) <br>
Not like this: [v2] <br>
![youtube-round](http://www.apkmirror.com/wp-content/themes/APKMirror/ap_resize/ap_resize.php?src=http%3A%2F%2Fwww.apkmirror.com%2Fwp-content%2Fuploads%2F2017%2F05%2F592d8e4da7994.png&w=128&h=128&q=100)

**Comment by keetrock46270** [comment] 2017-06-18 16:25
Correct. Sorry, I thought it would attach.

**Comment by zeevox** [comment] 2017-06-18 16:28
Exactly, that's the round icons I was talking about. The second one is the round icon, the first is the default icon. This isn't actually provided by the launcher, it's the app that picks how they look. 

The launcher can, however, through some nasty hacks, display the round ones or the default ones. I'm currently working on a pull request to enable a preference in settings that would allow you to pick which type you want.

**Comment by keetrock46270** [comment] 2017-06-18 16:29
Awesome! Love the app regardless. It's absolutely amazing! Thank you!

**Comment by amirzaidi** [comment] 2017-06-18 16:42
I don't want any settings that aren't in the Pixel Launcher, sorry. If you want it fork the code and revert this commit: https://github.com/amirzaidi/Launcher3/commit/50fa356d023b90ec760fc09942f5b5ecbd4fd008

(Except for the try/catch part, sorry about not making proper atomic commits)

**Closed as completed** 2017-06-18 22:21 UTC
