### ISSUE TITLE
Dock color

### ISSUE THREAD

**Issue by RikKoedoot** [amirzaidi/Launcher3#45] opened 2017-06-15 18:40 UTC
I have reset my phone, and reinstalled the launcher, but now the dock is fully transparent, not the semi transparent it was before, what is the problem?

**Comment by RWOne** [comment] 2017-06-15 18:53
Likely your Android version.

**Comment by amirzaidi** [comment] 2017-06-15 21:49
Duplicate of https://github.com/amirzaidi/Launcher3/issues/19

**Closed as completed by amirzaidi** 2017-06-15 21:49 UTC
