### ISSUE TITLE
2.0.1 Notification dots not always shown

### ISSUE THREAD

**Issue by korbendalos** [amirzaidi/Launcher3#115] opened 2017-08-25 07:59 UTC
Hi
Thanks again, great job as usual!
Just wanted to emphasize on some probable bug. Have just noticed that notification dots are not always shown. E.g. there was no dot on whatsup app when I've got a message, however the notification itself appeared on upper notification pane.
Thanks.

**Comment by korbendalos** [comment] 2017-08-25 08:01
P.S. samsung galaxy note5 android 7.0

**Comment by shiva39** [comment] 2017-08-25 14:25
Send me that link

**Comment by korbendalos** [comment] 2017-08-25 16:28
https://drive.google.com/file/d/0B7Jq7nRRv6UUblFKNXVibkRjVTA/view?usp=drivesdk

**Comment by amirzaidi** [comment] 2017-08-25 17:57
Is it a group chat? WhatsApp is a bit iffy there, but all other apps seem to work fine

**Comment by korbendalos** [comment] 2017-08-25 19:06
Nope, just single personal message. I've reassigned notification access for WhatsApp and rebooted device and dots seem to work fine for this app. Weird...
P.S. by the way - the same issue for Youtube, but rights reassign and device reboot didn't help.

**Comment by PR1D3S** [comment] 2017-08-26 11:01
Yes this is happening only with whatsapp...

**Comment by SethuSenthil** [comment] 2017-08-27 14:49
Do you have the beta version of WhatsApp? Or your phone's memory (ram) is full and won't allow the launcher to seek for notifications.

**Comment by PR1D3S** [comment] 2017-08-27 15:08
No i m not using beta version of whatsapp,and its not ram problem,notification dots working fine with other apps....if i get 1 notification on whatsapp dot not getting appear but when i get 2 then it appears....

**Comment by amirzaidi** [comment] 2017-08-27 15:19
I have the same issue with WhatsApp but I think it's related to the way WhatsApp handles notifications

**Comment by dbesoli** [comment] 2018-01-29 12:17
I've a similar case but it affects all the apps. After 24hour more or less working the dots dissapear on all applications.
I've Huawei P9 on Stock Nougat 7.0
And I think probably the issue is related to Huawei. With the "Rootless Pixel 2 launcher" from paphonb the problem is the same.
I've asked several times on its thread if anyone has the same problem but nobody has answered so, I suppose nobody has this issue.
I solve it removing the permissions to read notifications and granting it again.
rebooting doesn't solves the problem, only the explained above
Doens anyone else has this pb?

**Comment by amirzaidi** [comment] 2018-03-10 16:30
Copy paste from Telegram:

I have been researching the "bugged notification dots" too but it seems to be an Android bug that can only be fixed by rebooting the phone. It shouldn't occur unless you update the APK - and if that breaks the dots a reboot should keep it working until the next update. Search "notificationlistenerservice not starting" on Google to find more information, it has been a bug since Android 4.4 and has still not been properly fixed.

**Closed as completed by amirzaidi** 2018-03-10 16:30 UTC
Labels: bug
