### ISSUE TITLE
Calendar Icon is not LIve

### ISSUE THREAD

**Issue by devang98** [amirzaidi/Launcher3#17] opened 2017-06-13 14:28 UTC
In the Pixel Launcher - Andriod O version, the calendar icon was live - it showed the current date, this is not present in your version.

Is it possible to get that also.

**Comment by amirzaidi** [comment] 2017-06-13 14:41
Update to 1.1 or 1.2.

**Comment by devang98** [comment] 2017-06-13 14:46
could you send me the apk link ?

**Comment by amirzaidi** [comment] 2017-06-13 16:45
https://github.com/amirzaidi/Launcher3/releases/tag/Pixel-v1.2

**Comment by jmcn72** [comment] 2017-06-13 23:36
I installed 1.2 but the version in App info still shows as 1.0.  Apologies I'm a newb to github.

**Comment by RikKoedoot** [comment] 2017-06-14 05:17
If the appdrawer color is blue you have 1.2

**Comment by devang98** [comment] 2017-06-14 05:35
Thanks for the link, this worked perfectly.. now can you also help to share how we can change icon's if that is possible

**Comment by amirzaidi** [comment] 2017-06-14 06:35
@jmcn72 I do not update the version number in app info so I can always easily revert to older versions for testing without having to reinstall. So the only way to tell which version you're on is by the features and the APK name. 

@devang98 Icon pack support is not planned so far, maybe somewhere in the future.

**Comment by Dabrador** [comment] 2017-06-15 13:08
Updated to version 1.3 and the calendar icon does not show current day.  It shows the day I installed the update (yesterday).

**Comment by Dabrador** [comment] 2017-06-18 11:14
Version 1.4 still has this bug. Calendar icon is not live.

**Comment by amirzaidi** [comment] 2017-06-18 11:38
Does force closing the launcher fix it temporarily? I have a feeling it's related to the icon cache but when I manually change the date on my system settings the icon automatically updates for me

**Comment by Dabrador** [comment] 2017-06-18 11:51
Yes. Force closing or rebooting the phone fixes it temporarily

**Comment by amirzaidi** [comment] 2017-06-18 14:43
What happens if you manually change the system date instead of waiting for the day to end? Does it update then?

**Comment by Dabrador** [comment] 2017-06-18 22:16
When you manually change the date, the icon shows the updated date. For example I changed the date to the 19th (today is the 18th) and tie icon showed 19. I changed date settings back to automatic and the icon updated to the 18th, the correct date. It appears the problem is when the date changes based on the time at the end of the day.

**Comment by amirzaidi** [comment] 2017-06-18 22:27
Well the weird thing is that for me it does update, I've tested it before. What ROM/OS are you on? Maybe it doesn't send the intent when the date changes

**Comment by Dabrador** [comment] 2017-06-19 01:26
I'm on 6.01. The ROM is a stock based on marshmallow.

**Comment by amirzaidi** [comment] 2017-06-19 02:03
Which device?

**Comment by Dabrador** [comment] 2017-06-19 02:15
Motorola Droid Turbo

**Comment by amirzaidi** [comment] 2017-06-19 02:23
Could you send me a full logcat of what happens from 23:59 to 0:01?

**Comment by Dabrador** [comment] 2017-06-19 11:11
Could you let me know how to do that? Does it need to be taken at that time or can it be later?

**Comment by amirzaidi** [comment] 2017-06-19 11:23
You can take it later but I'm only interested in that part because that's where your system should send an intent that the date changed. There are tutorials on the internet for it, if you want me to fix it please look up how to do that :)

**Comment by Dabrador** [comment] 2017-06-19 12:46
Now this is strange. Some time between 7 and 8 am this morning, the icon changed to the correct date.

**Closed as completed** 2017-08-26 01:23 UTC
Labels: bug
