### ISSUE TITLE
Add pixel launcher 2 update 

### ISSUE THREAD

**Issue by NathanFrederick** [amirzaidi/Launcher3#272] opened 2017-10-13 14:10 UTC
The new pixel launcher 2 is on the APK mirror site Add pixel launcher 2 update and add Google now swipe the one from the APK mirror does not have Google now swipe just like the original pixel launcher have to set it as system app to show the Google Now swipe

**Comment by schliflo** [comment] 2017-10-13 22:36
duplicate of #259 and #271 -> please close

**Closed as completed** 2017-10-13 22:38 UTC
